export const CURRENCY_MAP: Record<string, { country: string; name: string }> = {
    AED: { country: 'United Arab Emirates', name: 'UAE Dirham' },
    AFN: { country: 'Afghanistan', name: 'Afghan Afghani' },
    ALL: { country: 'Albania', name: 'Albanian Lek' },
    AMD: { country: 'Armenia', name: 'Armenian Dram' },
    ANG: { country: 'Netherlands Antilles', name: 'Antillean Guilder' },
    AOA: { country: 'Angola', name: 'Angolan Kwanza' },
    ARS: { country: 'Argentina', name: 'Argentine Peso' },
    AUD: { country: 'Australia', name: 'Australian Dollar' },
    AWG: { country: 'Aruba', name: 'Aruban Florin' },
    AZN: { country: 'Azerbaijan', name: 'Azerbaijani Manat' },
    BAM: { country: 'Bosnia-Herzegovina', name: 'Convertible Mark' },
    BBD: { country: 'Barbados', name: 'Barbadian Dollar' },
    BDT: { country: 'Bangladesh', name: 'Bangladeshi Taka' },
    BGN: { country: 'Bulgaria', name: 'Bulgarian Lev' },
    BHD: { country: 'Bahrain', name: 'Bahraini Dinar' },
    BIF: { country: 'Burundi', name: 'Burundian Franc' },
    BMD: { country: 'Bermuda', name: 'Bermudan Dollar' },
    BND: { country: 'Brunei', name: 'Brunei Dollar' },
    BOB: { country: 'Bolivia', name: 'Bolivian Boliviano' },
    BRL: { country: 'Brazil', name: 'Brazilian Real' },
    BSD: { country: 'Bahamas', name: 'Bahamian Dollar' },
    BTC: { country: 'Digital', name: 'Bitcoin' },
    BTN: { country: 'Bhutan', name: 'Bhutanese Ngultrum' },
    BWP: { country: 'Botswana', name: 'Botswanan Pula' },
    BYN: { country: 'Belarus', name: 'Belarusian Ruble' },
    BZD: { country: 'Belize', name: 'Belize Dollar' },
    CAD: { country: 'Canada', name: 'Canadian Dollar' },
    CDF: { country: 'Congo', name: 'Congolese Franc' },
    CHF: { country: 'Switzerland', name: 'Swiss Franc' },
    CLP: { country: 'Chile', name: 'Chilean Peso' },
    CNY: { country: 'China', name: 'Chinese Yuan' },
    COP: { country: 'Colombia', name: 'Colombian Peso' },
    CRC: { country: 'Costa Rica', name: 'Costa Rican Colón' },
    CUP: { country: 'Cuba', name: 'Cuban Peso' },
    CVE: { country: 'Cape Verde', name: 'Cape Verdean Escudo' },
    CZK: { country: 'Czech Republic', name: 'Czech Koruna' },
    DJF: { country: 'Djibouti', name: 'Djiboutian Franc' },
    DKK: { country: 'Denmark', name: 'Danish Krone' },
    DOP: { country: 'Dominican Republic', name: 'Dominican Peso' },
    DZD: { country: 'Algeria', name: 'Algerian Dinar' },
    EGP: { country: 'Egypt', name: 'Egyptian Pound' },
    ERN: { country: 'Eritrea', name: 'Eritrean Nakfa' },
    ETB: { country: 'Ethiopia', name: 'Ethiopian Birr' },
    EUR: { country: 'European Union', name: 'Euro' },
    FJD: { country: 'Fiji', name: 'Fijian Dollar' },
    GBP: { country: 'United Kingdom', name: 'British Pound' },
    GEL: { country: 'Georgia', name: 'Georgian Lari' },
    GHS: { country: 'Ghana', name: 'Ghanaian Cedi' },
    GMD: { country: 'Gambia', name: 'Gambian Dalasi' },
    GNF: { country: 'Guinea', name: 'Guinean Franc' },
    GTQ: { country: 'Guatemala', name: 'Guatemalan Quetzal' },
    GYD: { country: 'Guyana', name: 'Guyanaese Dollar' },
    HKD: { country: 'Hong Kong', name: 'Hong Kong Dollar' },
    HNL: { country: 'Honduras', name: 'Honduran Lempira' },
    HRK: { country: 'Croatia', name: 'Croatian Kuna' },
    HTG: { country: 'Haiti', name: 'Haitian Gourde' },
    HUF: { country: 'Hungary', name: 'Hungarian Forint' },
    IDR: { country: 'Indonesia', name: 'Indonesian Rupee' },
    ILS: { country: 'Israel', name: 'Israeli New Shekel' },
    INR: { country: 'India', name: 'Indian Rupee' },
    IQD: { country: 'Iraq', name: 'Iraqi Dinar' },
    IRR: { country: 'Iran', name: 'Iranian Rial' },
    ISK: { country: 'Iceland', name: 'Icelandic Króna' },
    JMD: { country: 'Jamaica', name: 'Jamaican Dollar' },
    JOD: { country: 'Jordan', name: 'Jordanian Dinar' },
    JPY: { country: 'Japan', name: 'Japanese Yen' },
    KES: { country: 'Kenya', name: 'Kenyan Shilling' },
    KGS: { country: 'Kyrgyzstan', name: 'Kyrgystani Som' },
    KHR: { country: 'Cambodia', name: 'Cambodian Riel' },
    KMF: { country: 'Comoros', name: 'Comorian Franc' },
    KRW: { country: 'South Korea', name: 'South Korean Won' },
    KWD: { country: 'Kuwait', name: 'Kuwaiti Dinar' },
    KYD: { country: 'Cayman Islands', name: 'Cayman Islands Dollar' },
    KZT: { country: 'Kazakhstan', name: 'Kazakhstani Tenge' },
    LAK: { country: 'Laos', name: 'Laotian Kip' },
    LBP: { country: 'Lebanon', name: 'Lebanese Pound' },
    LKR: { country: 'Sri Lanka', name: 'Sri Lankan Rupee' },
    LRD: { country: 'Liberia', name: 'Liberian Dollar' },
    LSL: { country: 'Lesotho', name: 'Lesotho Loti' },
    LYD: { country: 'Libya', name: 'Libyan Dinar' },
    MAD: { country: 'Morocco', name: 'Moroccan Dirham' },
    MDL: { country: 'Moldova', name: 'Moldovan Leu' },
    MGA: { country: 'Madagascar', name: 'Malagasy Ariary' },
    MKD: { country: 'North Macedonia', name: 'Macedonian Denar' },
    MMK: { country: 'Myanmar', name: 'Myanmar Kyat' },
    MNT: { country: 'Mongolia', name: 'Mongolian Tugrik' },
    MOP: { country: 'Macau', name: 'Macanese Pataca' },
    MUR: { country: 'Mauritius', name: 'Mauritian Rupee' },
    MVR: { country: 'Maldives', name: 'Maldivian Rufiyaa' },
    MWK: { country: 'Malawi', name: 'Malawian Kwacha' },
    MXN: { country: 'Mexico', name: 'Mexican Peso' },
    MYR: { country: 'Malaysia', name: 'Malaysian Ringgit' },
    MZN: { country: 'Mozambique', name: 'Mozambican Metical' },
    NAD: { country: 'Namibia', name: 'Namibian Dollar' },
    NGN: { country: 'Nigeria', name: 'Nigerian Naira' },
    NIO: { country: 'Nicaragua', name: 'Nicaraguan Córdoba' },
    NOK: { country: 'Norway', name: 'Norwegian Krone' },
    NPR: { country: 'Nepal', name: 'Nepalese Rupee' },
    NZD: { country: 'New Zealand', name: 'New Zealand Dollar' },
    OMR: { country: 'Oman', name: 'Omani Rial' },
    PAB: { country: 'Panama', name: 'Panamanian Balboa' },
    PEN: { country: 'Peru', name: 'Peruvian Sol' },
    PGK: { country: 'Papua New Guinea', name: 'Papua New Guinean Kina' },
    PHP: { country: 'Philippines', name: 'Philippine Peso' },
    PKR: { country: 'Pakistan', name: 'Pakistani Rupee' },
    PLN: { country: 'Poland', name: 'Polish Zloty' },
    PYG: { country: 'Paraguay', name: 'Paraguayan Guarani' },
    QAR: { country: 'Qatar', name: 'Qatari Rial' },
    RON: { country: 'Romania', name: 'Romanian Leu' },
    RSD: { country: 'Serbia', name: 'Serbian Dinar' },
    RUB: { country: 'Russia', name: 'Russian Ruble' },
    RWF: { country: 'Rwanda', name: 'Rwandan Franc' },
    SAR: { country: 'Saudi Arabia', name: 'Saudi Riyal' },
    SBD: { country: 'Solomon Islands', name: 'Solomon Islands Dollar' },
    SCR: { country: 'Seychelles', name: 'Seychellois Rupee' },
    SDG: { country: 'Sudan', name: 'Sudanese Pound' },
    SEK: { country: 'Sweden', name: 'Swedish Krona' },
    SGD: { country: 'Singapore', name: 'Singapore Dollar' },
    SLL: { country: 'Sierra Leone', name: 'Sierra Leonean Leone' },
    SOS: { country: 'Somalia', name: 'Somali Shilling' },
    SRD: { country: 'Suriname', name: 'Surinamese Dollar' },
    SSP: { country: 'South Sudan', name: 'South Sudanese Pound' },
    SYP: { country: 'Syria', name: 'Syrian Pound' },
    SZL: { country: 'Eswatini', name: 'Swazi Lilangeni' },
    THB: { country: 'Thailand', name: 'Thai Baht' },
    TJS: { country: 'Tajikistan', name: 'Tajikistani Somoni' },
    TMT: { country: 'Turkmenistan', name: 'Turkmenistani Manat' },
    TND: { country: 'Tunisia', name: 'Tunisian Dinar' },
    TOP: { country: 'Tonga', name: 'Tongan Paʻanga' },
    TRY: { country: 'Turkey', name: 'Turkish Lira' },
    TTD: { country: 'Trinidad and Tobago', name: 'Trinidad Dollar' },
    TWD: { country: 'Taiwan', name: 'New Taiwan Dollar' },
    TZS: { country: 'Tanzania', name: 'Tanzanian Shilling' },
    UAH: { country: 'Ukraine', name: 'Ukrainian Hryvnia' },
    UGX: { country: 'Uganda', name: 'Ugandan Shilling' },
    USD: { country: 'United States', name: 'US Dollar' },
    UYU: { country: 'Uruguay', name: 'Uruguayan Peso' },
    UZS: { country: 'Uzbekistan', name: 'Uzbekistan Som' },
    VES: { country: 'Venezuela', name: 'Venezuelan Bolívar' },
    VND: { country: 'Vietnam', name: 'Vietnamese Dong' },
    VUV: { country: 'Vanuatu', name: 'Vanuatu Vatu' },
    WST: { country: 'Samoa', name: 'Samoan Tala' },
    XAF: { country: 'Central Africa', name: 'CFA Franc BEAC' },
    XCD: { country: 'East Caribbean', name: 'East Caribbean Dollar' },
    XOF: { country: 'West Africa', name: 'CFA Franc BCEAO' },
    XPF: { country: 'French Polynesia', name: 'CFP Franc' },
    YER: { country: 'Yemen', name: 'Yemeni Rial' },
    ZAR: { country: 'South Africa', name: 'South African Rand' },
    ZMW: { country: 'Zambia', name: 'Zambian Kwacha' },
    ZWL: { country: 'Zimbabwe', name: 'Zimbabwean Dollar' },
};

export function getCurrencyInfo(currencyCode: string) {
    const fallbackCountry = currencyCode.substring(0, 2);

    // Special multi-nation flags & overrides
    const specialFlags: Record<string, string> = {
        EUR: '🇪🇺',
        BTC: '₿',
        XAF: '🇨🇲', // Represents Central Africa
        XOF: '🇸🇳', // Represents West Africa
        XCD: '🇦🇬', // Represents East Caribbean
        XPF: '🇵🇫', // Represents French Polynesia
    };

    // Converts the 2-letter country code (e.g. "US") into the corresponding Flag Emoji (🇺🇸)
    const flag =
        specialFlags[currencyCode] ||
        String.fromCodePoint(
            ...[...fallbackCountry].map((c) => c.charCodeAt(0) + 127397)
        );

    const data = CURRENCY_MAP[currencyCode] || {
        country: 'Global',
        name: currencyCode,
    };

    return { ...data, flag };
}